### ISSUE TITLE
Mock TypeError custom override

### ISSUE THREAD

**Issue by dipsaus9** [anymaniax/orval#1202]
## When using the override mock option the TypeCheck is too strict

With the release of 6.24 orval introduced the return type for the mws files, see #1171. 
When using the override option for certain opperations the TypeCheck is too strict, without any options to set the type.
As orval uses `js` to parse the document we can not add extra type declarations to the config. This breaks our 

1. Define a override operation in the `orval.config.js`
2. Set the option `mock` to `true`
3. Get a type error when override Enums or literals

## What happens?

TypeErrors in the `.msw.ts` file

## What were you expecting to happen?

Not sure what the best solution is. The return type is a nice feature, but maybe we should be able to override the return value, or not set it in case of the override function in the config. As orval uses JavaScript and not TypeScript we can not strictly type the return value in the config.

## Any logs, error output, etc?

Not at the moment, if you need more details I can add it. 

## Any other comments?

Open for suggestions.

**Comment by soartec-lab** [comment]
Similar to https://github.com/anymaniax/orval/issues/1201

**Comment by soartec-lab** [comment]
@dipsaus9 
Thank you for made this report. 
I would like to understand this problem correctly, so could you please tell me the error message that is output?

**Comment by soartec-lab** [comment]
I have fixed the issue where it did not work correctly by #1205  when enum types were included.

**Comment by dipsaus9** [comment]
I'll test it as the release is out there. 
To clarify the issue:

With the return type now added to the `.msw.ts` file, the type check is more strict.
As an example, if the Schema of `Dog` has an literal or enum as a return value, orval uses the following code:

```
faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(DogType)),   // DogType is not imported
    undefined,
  ])
```

This is great.

But if you want to override this value with the override function we can not type the enum. As an example in the config we currently have.

```
	override: {
		operations: {
           api_countries_get_collection: {
            mock: {
              data: () => {
                const countries = ["GB"] // We limit the Enum list here due to testing security

				return countries
                }
              },
            },
          },
```

The expected return type is a list of enum.

In the previous version this would result in no errors. With the strict return type the `countries` const now types to a string.
And we have no way to update this to a typed value as the config uses common js.

Hope this clarifies the issue.

**Comment by soartec-lab** [comment]
Hi, @dipsaus9 

Since we released "v6.25.0" this issue has been fixed 👍

**Comment by dipsaus9** [comment]
@soartec-lab  Release v6.25.0 did not fix our issue. 
I opened a PR that can be a fix #1229
