### ISSUE TITLE
TypeError: Cannot read property 'components' of undefined with linked schemas

### ISSUE THREAD

**Issue by Talor-A** [anymaniax/orval#259]
## What are the steps to reproduce this issue?
1. have an operation in the spec (main file "A") whose response is a `$ref` to a schema B in a separate file (file "B")
2. have the schema B with a property which is a `$ref` to schema C in file "C"
3. try to generate a client library, the generation will fail.

## What happens?

orval fails to recognize the third file, and no code can be generated. the following error is shown in output:

```
TypeError: Cannot read property 'components' of undefined
```

## What were you expecting to happen?
I would expect to have file A reference file B, which references file C, and all compile correctly.

## Any logs, error output, etc?
my config:
```ts
export default defineConfig({
  'my-service-name': {
    output: {
      mode: 'split',
      workspace: './generated-client/src/lib',
      target: './my-service-name',

      client: 'react-query',
      mock: true,
      clean: true,
      prettier: true,
      override: {
        mutator: {
          path: mutatorLocation,
          name: 'injectAxios',
        },
      },
    },

    input: {
      target: specLocation,
    },
  },
});
```

## Reproduction

File A (api.yaml)
```yaml
openapi: '3.0.0'
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /my-path:
    put:
      tags:
        - putPet
      operationId: putPet
      requestBody:
        content:
          'application/json':
            schema:
              $ref: "schemas/Pet.yaml#/components/schemas/Pet"
        required: true
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: "schemas/Pet.yaml#/components/schemas/Pet"
```
File B (schemas/Pet.yaml):
```yaml
openapi: 3.0.2
info:
  title: PetStore
  version: 1.0.0
paths: {}
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        owner:
          $ref: "Person.yaml#/components/schemas/Person"
```
File C: (schemas/Person.yaml):
```yaml
openapi: 3.0.2
info:
  title: PetStore
  version: 1.0.0
paths: {}
components:
  schemas:
    Person:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
```
I hope this is enough information to reproduce. I can post a repository if it helps. Unfortunately I can't generate my schema without this, as we have a very large service that needs to be split into many files.

I am really enjoying using orval thus far, and am happy to help out with any other details you might need. if you can point me to the right place in the code I can investigate and look for a fix. thanks @anymaniax for all your hard work on this library

## What versions are you using?
**Operating System:** MacOS Big Sur 11.6.1
**Package Version:** 6.3.0 (latest at time of writing)
**Browser Version:** n/a

**Comment by anymaniax** [comment]
Should be fixed with `6.4.0` can you test when you have time, please?

**Comment by anymaniax** [comment]
Closing this issue since it's normally fixed. Don't hesitate if you have any problem

**Comment by Talor-A** [comment]
I still see this issue, and do not with my fork. I will try to reproduce the problem more in detail and reopen if I can get anywhere with it.

**Comment by Talor-A** [comment]
@anymaniax the fix worked, the issue for me was that with multiple files all of them need to be valid openAPI, aka the need this at the top:
```yaml

openapi: 3.0.2
info:
  title: <My Title>
  version: 1.0.0
paths: {}
components:
  schemas:
    MySchema: ...
```

once I added this to all files generation worked with latest version (`6.5`). thanks again for your help!

**Comment by anymaniax** [comment]
@Talor-A ok top! thanks for the feedback
