### ISSUE TITLE
Can't generate code with ranged Typescript version

### ISSUE THREAD

**Issue by algoshipda** [anymaniax/orval#531]
## What are the steps to reproduce this issue?

1. Set the Typescript version to `    "typescript": ">=4.3.4 <5.0.0"` from package.json
2. Run the code generation. 

## What happens?
It will throw an error `Oups... 🍻. An Error occurred while splitting => Error: Invalid argument not valid semver ('>=4.3.4 <5.0.0' received)`

## What were you expecting to happen?

The code should be generated

## Any logs, error output, etc?
`Oups... 🍻. An Error occurred while splitting => Error: Invalid argument not valid semver ('>=4.3.4 <5.0.0' received)`

## Any other comments?
- As far as I observed, this error was came from `src/core/writers/target.ts` and  `compare` function in `compare-versions`
- How about adding the typescriptVersion property to orval config to explicitly specify the typescript version? Right now, it depends on the generator package's typescript version, but in my use case, I have two separate projects. The first one is generated code project, and the other is using that codes, which means they could be different typescript versions.
- My workaround is [here](https://github.com/anymaniax/orval/commit/458550b5e207cf09766de81fed9ce034d769b4c9)

## What versions are you using?

**Operating System: macOS Monterey 12.1
**Package Version: 6.7.1
**Browser Version: x

**Comment by anymaniax** [comment]
should be fixed in the next version

**Comment by melloware** [comment]
OK I just ran into this too with `typescript: latest` as well

**Comment by anymaniax** [comment]
Should be fixed right now

**Comment by melloware** [comment]
Still doesn't work with "latest" i get "An Error occurred while writing file => Error: Invalid argument not valid semver ('latest' received)"

**Comment by anymaniax** [comment]
@melloware fixed

**Comment by melloware** [comment]
As always you are the best!

**Comment by anymaniax** [comment]
should be fixed with `6.10.2`

**Comment by mrxsal** [comment]
Got the same error with `"typescript": "*"`
